/* Shared Use License: This file is owned by Derivative Inc. (Derivative)
* and can only be used, and/or modified for use, in conjunction with
* Derivative's TouchDesigner software, and only if you are a licensee who has
* accepted Derivative's TouchDesigner license or assignment agreement
* (which also govern the use of this file). You may share or redistribute
* a modified version of this file provided the following conditions are met:
*
* 1. The shared file or redistribution must retain the information set out
* above and this list of conditions.
* 2. Derivative's name (Derivative Inc.) or its trademarks may not be used
* to endorse or promote products derived from this file without specific
* prior written permission from Derivative.
*/

#include "D3D12TouchUtils.h"

#include "ID3D12DynamicRHI.h"
#include "Logging.h"

namespace UE::TouchEngine::D3DX12
{
	// Copy from D3D12Util.h: GetPlatformTextureResourceFormat with additions
	const TCHAR* GetD3D12TextureFormatString(DXGI_FORMAT TextureFormat)
	{
		static const TCHAR* EmptyString = TEXT("");
		const TCHAR* TextureFormatText = EmptyString;
#define D3DFORMATCASE(x) case x: TextureFormatText = TEXT(#x); break;
		switch (TextureFormat)
		{
			D3DFORMATCASE(DXGI_FORMAT_UNKNOWN)
			D3DFORMATCASE(DXGI_FORMAT_R32G32B32A32_TYPELESS)
			D3DFORMATCASE(DXGI_FORMAT_R32G32B32A32_FLOAT)
			D3DFORMATCASE(DXGI_FORMAT_R32G32B32A32_UINT)
			D3DFORMATCASE(DXGI_FORMAT_R32G32B32A32_SINT)
			D3DFORMATCASE(DXGI_FORMAT_R32G32B32_TYPELESS)
			D3DFORMATCASE(DXGI_FORMAT_R32G32B32_FLOAT)
			D3DFORMATCASE(DXGI_FORMAT_R32G32B32_UINT)
			D3DFORMATCASE(DXGI_FORMAT_R32G32B32_SINT)
			D3DFORMATCASE(DXGI_FORMAT_R16G16B16A16_TYPELESS)
			D3DFORMATCASE(DXGI_FORMAT_R16G16B16A16_FLOAT)
			D3DFORMATCASE(DXGI_FORMAT_R16G16B16A16_UNORM)
			D3DFORMATCASE(DXGI_FORMAT_R16G16B16A16_UINT)
			D3DFORMATCASE(DXGI_FORMAT_R16G16B16A16_SNORM)
			D3DFORMATCASE(DXGI_FORMAT_R16G16B16A16_SINT)
			D3DFORMATCASE(DXGI_FORMAT_R32G32_TYPELESS)
			D3DFORMATCASE(DXGI_FORMAT_R32G32_FLOAT)
			D3DFORMATCASE(DXGI_FORMAT_R32G32_UINT)
			D3DFORMATCASE(DXGI_FORMAT_R32G32_SINT)
			D3DFORMATCASE(DXGI_FORMAT_R32G8X24_TYPELESS)
			D3DFORMATCASE(DXGI_FORMAT_D32_FLOAT_S8X24_UINT)
			D3DFORMATCASE(DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS)
			D3DFORMATCASE(DXGI_FORMAT_X32_TYPELESS_G8X24_UINT)
			D3DFORMATCASE(DXGI_FORMAT_R10G10B10A2_TYPELESS)
			D3DFORMATCASE(DXGI_FORMAT_R10G10B10A2_UNORM)
			D3DFORMATCASE(DXGI_FORMAT_R10G10B10A2_UINT)
			D3DFORMATCASE(DXGI_FORMAT_R11G11B10_FLOAT)
			D3DFORMATCASE(DXGI_FORMAT_R8G8B8A8_TYPELESS)
			D3DFORMATCASE(DXGI_FORMAT_R8G8B8A8_UNORM)
			D3DFORMATCASE(DXGI_FORMAT_R8G8B8A8_UNORM_SRGB)
			D3DFORMATCASE(DXGI_FORMAT_R8G8B8A8_UINT)
			D3DFORMATCASE(DXGI_FORMAT_R8G8B8A8_SNORM)
			D3DFORMATCASE(DXGI_FORMAT_R8G8B8A8_SINT)
			D3DFORMATCASE(DXGI_FORMAT_R16G16_TYPELESS)
			D3DFORMATCASE(DXGI_FORMAT_R16G16_FLOAT)
			D3DFORMATCASE(DXGI_FORMAT_R16G16_UNORM)
			D3DFORMATCASE(DXGI_FORMAT_R16G16_UINT)
			D3DFORMATCASE(DXGI_FORMAT_R16G16_SNORM)
			D3DFORMATCASE(DXGI_FORMAT_R16G16_SINT)
			D3DFORMATCASE(DXGI_FORMAT_R32_TYPELESS)
			D3DFORMATCASE(DXGI_FORMAT_D32_FLOAT)
			D3DFORMATCASE(DXGI_FORMAT_R32_FLOAT)
			D3DFORMATCASE(DXGI_FORMAT_R32_UINT)
			D3DFORMATCASE(DXGI_FORMAT_R32_SINT)
			D3DFORMATCASE(DXGI_FORMAT_R24G8_TYPELESS)
			D3DFORMATCASE(DXGI_FORMAT_D24_UNORM_S8_UINT)
			D3DFORMATCASE(DXGI_FORMAT_R24_UNORM_X8_TYPELESS)
			D3DFORMATCASE(DXGI_FORMAT_X24_TYPELESS_G8_UINT)
			D3DFORMATCASE(DXGI_FORMAT_R8G8_TYPELESS)
			D3DFORMATCASE(DXGI_FORMAT_R8G8_UNORM)
			D3DFORMATCASE(DXGI_FORMAT_R8G8_UINT)
			D3DFORMATCASE(DXGI_FORMAT_R8G8_SNORM)
			D3DFORMATCASE(DXGI_FORMAT_R8G8_SINT)
			D3DFORMATCASE(DXGI_FORMAT_R16_TYPELESS)
			D3DFORMATCASE(DXGI_FORMAT_R16_FLOAT)
			D3DFORMATCASE(DXGI_FORMAT_D16_UNORM)
			D3DFORMATCASE(DXGI_FORMAT_R16_UNORM)
			D3DFORMATCASE(DXGI_FORMAT_R16_UINT)
			D3DFORMATCASE(DXGI_FORMAT_R16_SNORM)
			D3DFORMATCASE(DXGI_FORMAT_R16_SINT)
			D3DFORMATCASE(DXGI_FORMAT_R8_TYPELESS)
			D3DFORMATCASE(DXGI_FORMAT_R8_UNORM)
			D3DFORMATCASE(DXGI_FORMAT_R8_UINT)
			D3DFORMATCASE(DXGI_FORMAT_R8_SNORM)
			D3DFORMATCASE(DXGI_FORMAT_R8_SINT)
			D3DFORMATCASE(DXGI_FORMAT_A8_UNORM)
			D3DFORMATCASE(DXGI_FORMAT_R1_UNORM)
			D3DFORMATCASE(DXGI_FORMAT_R9G9B9E5_SHAREDEXP)
			D3DFORMATCASE(DXGI_FORMAT_R8G8_B8G8_UNORM)
			D3DFORMATCASE(DXGI_FORMAT_G8R8_G8B8_UNORM)
			D3DFORMATCASE(DXGI_FORMAT_BC1_TYPELESS)
			D3DFORMATCASE(DXGI_FORMAT_BC1_UNORM)
			D3DFORMATCASE(DXGI_FORMAT_BC1_UNORM_SRGB)
			D3DFORMATCASE(DXGI_FORMAT_BC2_TYPELESS)
			D3DFORMATCASE(DXGI_FORMAT_BC2_UNORM)
			D3DFORMATCASE(DXGI_FORMAT_BC2_UNORM_SRGB)
			D3DFORMATCASE(DXGI_FORMAT_BC3_TYPELESS)
			D3DFORMATCASE(DXGI_FORMAT_BC3_UNORM)
			D3DFORMATCASE(DXGI_FORMAT_BC3_UNORM_SRGB)
			D3DFORMATCASE(DXGI_FORMAT_BC4_TYPELESS)
			D3DFORMATCASE(DXGI_FORMAT_BC4_UNORM)
			D3DFORMATCASE(DXGI_FORMAT_BC4_SNORM)
			D3DFORMATCASE(DXGI_FORMAT_BC5_TYPELESS)
			D3DFORMATCASE(DXGI_FORMAT_BC5_UNORM)
			D3DFORMATCASE(DXGI_FORMAT_BC5_SNORM)
			D3DFORMATCASE(DXGI_FORMAT_B5G6R5_UNORM)
			D3DFORMATCASE(DXGI_FORMAT_B5G5R5A1_UNORM)
			D3DFORMATCASE(DXGI_FORMAT_B8G8R8A8_UNORM)
			D3DFORMATCASE(DXGI_FORMAT_B8G8R8X8_UNORM)
			D3DFORMATCASE(DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM)
			D3DFORMATCASE(DXGI_FORMAT_B8G8R8A8_TYPELESS)
			D3DFORMATCASE(DXGI_FORMAT_B8G8R8A8_UNORM_SRGB)
			D3DFORMATCASE(DXGI_FORMAT_B8G8R8X8_TYPELESS)
			D3DFORMATCASE(DXGI_FORMAT_B8G8R8X8_UNORM_SRGB)
			D3DFORMATCASE(DXGI_FORMAT_BC6H_TYPELESS)
			D3DFORMATCASE(DXGI_FORMAT_BC6H_UF16)
			D3DFORMATCASE(DXGI_FORMAT_BC6H_SF16)
			D3DFORMATCASE(DXGI_FORMAT_BC7_TYPELESS)
			D3DFORMATCASE(DXGI_FORMAT_BC7_UNORM)
			D3DFORMATCASE(DXGI_FORMAT_BC7_UNORM_SRGB)
			D3DFORMATCASE(DXGI_FORMAT_AYUV)
			D3DFORMATCASE(DXGI_FORMAT_Y410)
			D3DFORMATCASE(DXGI_FORMAT_Y416)
			D3DFORMATCASE(DXGI_FORMAT_NV12)
			D3DFORMATCASE(DXGI_FORMAT_P010)
			D3DFORMATCASE(DXGI_FORMAT_P016)
			D3DFORMATCASE(DXGI_FORMAT_420_OPAQUE)
			D3DFORMATCASE(DXGI_FORMAT_YUY2)
			D3DFORMATCASE(DXGI_FORMAT_Y210)
			D3DFORMATCASE(DXGI_FORMAT_Y216)
			D3DFORMATCASE(DXGI_FORMAT_NV11)
			D3DFORMATCASE(DXGI_FORMAT_AI44)
			D3DFORMATCASE(DXGI_FORMAT_IA44)
			D3DFORMATCASE(DXGI_FORMAT_P8)
			D3DFORMATCASE(DXGI_FORMAT_A8P8)
			D3DFORMATCASE(DXGI_FORMAT_B4G4R4A4_UNORM)

			D3DFORMATCASE(DXGI_FORMAT_P208)
			D3DFORMATCASE(DXGI_FORMAT_V208)
			D3DFORMATCASE(DXGI_FORMAT_V408)


			D3DFORMATCASE(DXGI_FORMAT_SAMPLER_FEEDBACK_MIN_MIP_OPAQUE)
			D3DFORMATCASE(DXGI_FORMAT_SAMPLER_FEEDBACK_MIP_REGION_USED_OPAQUE)


			D3DFORMATCASE(DXGI_FORMAT_FORCE_UINT)
		default: TextureFormatText = EmptyString;
		}
#undef D3DFORMATCASE
		return TextureFormatText;
	}
	
	EPixelFormat ConvertD3FormatToPixelFormat(DXGI_FORMAT Format, bool& bIsSRGB)
	{
		// Some existing mappings can be found in D3D12RHIPrivate.h for reference: GetPlatformTextureResourceFormat
		
#define MAP_FORMAT(DX_Format, UE_Format) \
	case DX_Format: return UE_Format;
#define MAP_FORMAT_SRGB(DX_Format, UE_Format) \
case DX_Format: bIsSRGB = true; return UE_Format;
		
		bIsSRGB = false;
		switch (Format)
		{
			MAP_FORMAT(DXGI_FORMAT_R8_UNORM,           PF_G8) //not PF_R8?
			MAP_FORMAT(DXGI_FORMAT_R16_UNORM,          PF_G16)
			MAP_FORMAT(DXGI_FORMAT_R32G32B32A32_FLOAT, PF_A32B32G32R32F)
			MAP_FORMAT(DXGI_FORMAT_B8G8R8A8_UNORM,     PF_B8G8R8A8)
			MAP_FORMAT_SRGB(DXGI_FORMAT_B8G8R8A8_UNORM_SRGB,     PF_B8G8R8A8)
			MAP_FORMAT(DXGI_FORMAT_R16G16B16A16_FLOAT, PF_FloatRGBA)
			MAP_FORMAT(DXGI_FORMAT_R32_FLOAT,          PF_R32_FLOAT)
			MAP_FORMAT(DXGI_FORMAT_R16G16_UNORM,       PF_G16R16)
			MAP_FORMAT(DXGI_FORMAT_R16G16_FLOAT,       PF_G16R16F)
			MAP_FORMAT(DXGI_FORMAT_R32G32_FLOAT,       PF_G32R32F)
			MAP_FORMAT(DXGI_FORMAT_R10G10B10A2_UNORM,  PF_A2B10G10R10)
			MAP_FORMAT(DXGI_FORMAT_R16_FLOAT,          PF_R16F)
			MAP_FORMAT(DXGI_FORMAT_R11G11B10_FLOAT,    PF_FloatR11G11B10)
			MAP_FORMAT(DXGI_FORMAT_R8G8B8A8_UNORM,     PF_R8G8B8A8)
			MAP_FORMAT_SRGB(DXGI_FORMAT_R8G8B8A8_UNORM_SRGB,     PF_R8G8B8A8)
			MAP_FORMAT(DXGI_FORMAT_R8G8_UNORM,         PF_R8G8)
			MAP_FORMAT(DXGI_FORMAT_R16G16B16A16_UNORM, PF_R16G16B16A16_UNORM)

			// Compressed types
			MAP_FORMAT(DXGI_FORMAT_B8G8R8A8_TYPELESS,	PF_B8G8R8A8)
			MAP_FORMAT(DXGI_FORMAT_BC1_TYPELESS,		PF_DXT1)
			MAP_FORMAT(DXGI_FORMAT_BC1_UNORM,			PF_DXT1)
			MAP_FORMAT_SRGB(DXGI_FORMAT_BC1_UNORM_SRGB,	PF_DXT1)
			MAP_FORMAT(DXGI_FORMAT_BC2_TYPELESS,		PF_DXT3)
			MAP_FORMAT(DXGI_FORMAT_BC2_UNORM,			PF_DXT3)
			MAP_FORMAT_SRGB(DXGI_FORMAT_BC2_UNORM_SRGB,	PF_DXT3)
			MAP_FORMAT(DXGI_FORMAT_BC3_TYPELESS,		PF_DXT5)
			MAP_FORMAT(DXGI_FORMAT_BC3_UNORM,			PF_DXT5)
			MAP_FORMAT(DXGI_FORMAT_BC3_UNORM_SRGB,		PF_DXT5)
			MAP_FORMAT(DXGI_FORMAT_BC4_TYPELESS,		PF_BC4)
			MAP_FORMAT(DXGI_FORMAT_BC4_UNORM,			PF_BC4)
			MAP_FORMAT(DXGI_FORMAT_BC5_TYPELESS,		PF_BC5)
			MAP_FORMAT(DXGI_FORMAT_BC5_UNORM,			PF_BC5)
			MAP_FORMAT(DXGI_FORMAT_BC6H_TYPELESS,		PF_BC6H)
			MAP_FORMAT(DXGI_FORMAT_BC6H_UF16,			PF_BC6H)
			MAP_FORMAT(DXGI_FORMAT_BC7_TYPELESS,		PF_BC7)
			MAP_FORMAT(DXGI_FORMAT_BC7_UNORM,			PF_BC7)
			MAP_FORMAT_SRGB(DXGI_FORMAT_BC7_UNORM_SRGB,	PF_BC7)

			default:
				return PF_Unknown;
		}

#undef MAP_FORMAT
#undef MAP_FORMAT_SRGB
	}

	DXGI_FORMAT ToTypedDXGIFormat(EPixelFormat Format, bool bIsSRGB)
	{
#define MAP_FORMAT(UE_Format, DX_Format) \
	case UE_Format: return DX_Format;
#define MAP_FORMAT_SRGB(UE_Format, DX_Format, DX_Format_sRGB) \
	case UE_Format: return bIsSRGB ? DX_Format_sRGB : DX_Format;
		
 		switch (Format)
 		{
 			MAP_FORMAT(PF_G8,                 DXGI_FORMAT_R8_UNORM)
			MAP_FORMAT(PF_G16,                DXGI_FORMAT_R16_UNORM)
			MAP_FORMAT(PF_A32B32G32R32F,      DXGI_FORMAT_R32G32B32A32_FLOAT)
			MAP_FORMAT_SRGB(PF_B8G8R8A8,      DXGI_FORMAT_B8G8R8A8_UNORM,  DXGI_FORMAT_B8G8R8A8_UNORM_SRGB)
			MAP_FORMAT(PF_FloatRGB,           DXGI_FORMAT_R16G16B16A16_FLOAT)
			MAP_FORMAT(PF_FloatRGBA,          DXGI_FORMAT_R16G16B16A16_FLOAT)
			MAP_FORMAT(PF_R32_FLOAT,          DXGI_FORMAT_R32_FLOAT)
			MAP_FORMAT(PF_G16R16,             DXGI_FORMAT_R16G16_UNORM)
			MAP_FORMAT(PF_G16R16F,            DXGI_FORMAT_R16G16_FLOAT)
			MAP_FORMAT(PF_G32R32F,            DXGI_FORMAT_R32G32_FLOAT)
			MAP_FORMAT(PF_A2B10G10R10,        DXGI_FORMAT_R10G10B10A2_UNORM)
			MAP_FORMAT(PF_R16F,               DXGI_FORMAT_R16_FLOAT)
			MAP_FORMAT(PF_FloatR11G11B10,     DXGI_FORMAT_R11G11B10_FLOAT)
			MAP_FORMAT_SRGB(PF_R8G8B8A8,      DXGI_FORMAT_R8G8B8A8_UNORM, DXGI_FORMAT_R8G8B8A8_UNORM_SRGB)
			MAP_FORMAT(PF_R8G8,               DXGI_FORMAT_R8G8_UNORM)
			MAP_FORMAT(PF_A16B16G16R16,       DXGI_FORMAT_R16G16B16A16_UNORM)
			MAP_FORMAT(PF_R16G16B16A16_UNORM, DXGI_FORMAT_R16G16B16A16_UNORM)

 			// Compressed types
			MAP_FORMAT_SRGB(PF_DXT1,			DXGI_FORMAT_BC1_UNORM, DXGI_FORMAT_BC1_UNORM_SRGB)
			MAP_FORMAT_SRGB(PF_DXT3,			DXGI_FORMAT_BC2_UNORM, DXGI_FORMAT_BC2_UNORM_SRGB)
			MAP_FORMAT_SRGB(PF_DXT5,			DXGI_FORMAT_BC3_UNORM, DXGI_FORMAT_BC3_UNORM_SRGB)
			MAP_FORMAT(PF_BC4,					DXGI_FORMAT_BC4_UNORM)
			MAP_FORMAT(PF_BC5,					DXGI_FORMAT_BC5_UNORM)
			MAP_FORMAT(PF_BC6H,					DXGI_FORMAT_BC6H_UF16)
			MAP_FORMAT_SRGB(PF_BC7,				DXGI_FORMAT_BC7_UNORM, DXGI_FORMAT_BC7_UNORM_SRGB)
 			
		default:
			return DXGI_FORMAT_UNKNOWN;
 		}

#undef MAP_FORMAT
#undef MAP_FORMAT_SRGB
	}

	bool IsTypeless(DXGI_FORMAT Format)
	{
 		switch (Format)
 		{
 		case DXGI_FORMAT_R32G32B32A32_TYPELESS:
		case DXGI_FORMAT_R32G32B32_TYPELESS:
		case DXGI_FORMAT_R16G16B16A16_TYPELESS:
		case DXGI_FORMAT_R32G32_TYPELESS:
		case DXGI_FORMAT_R32G8X24_TYPELESS:
		case DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS:
		case DXGI_FORMAT_X32_TYPELESS_G8X24_UINT:
		case DXGI_FORMAT_R10G10B10A2_TYPELESS:
		case DXGI_FORMAT_R8G8B8A8_TYPELESS:
		case DXGI_FORMAT_R16G16_TYPELESS:
		case DXGI_FORMAT_R32_TYPELESS:
		case DXGI_FORMAT_R24G8_TYPELESS:
		case DXGI_FORMAT_R24_UNORM_X8_TYPELESS:
		case DXGI_FORMAT_X24_TYPELESS_G8_UINT:
		case DXGI_FORMAT_R8G8_TYPELESS:
		case DXGI_FORMAT_R16_TYPELESS:
		case DXGI_FORMAT_R8_TYPELESS:
		case DXGI_FORMAT_BC1_TYPELESS:
		case DXGI_FORMAT_BC2_TYPELESS:
		case DXGI_FORMAT_BC3_TYPELESS:
		case DXGI_FORMAT_BC4_TYPELESS:
		case DXGI_FORMAT_BC5_TYPELESS:
		case DXGI_FORMAT_B8G8R8A8_TYPELESS:
		case DXGI_FORMAT_B8G8R8X8_TYPELESS:
		case DXGI_FORMAT_BC6H_TYPELESS:
		case DXGI_FORMAT_BC7_TYPELESS:
 			return true;
 		default:
 			return false;
 		}
	}
}
